### ISSUE TITLE
question: reconnect

### ISSUE THREAD

**Issue by p0nt** [Atem18/kraky#32]
Hi,

Solid work Atem18! Thank you.

Does this automatically reconnect after for example maintenance?

Thanks in advance,

p0nts

**Comment by Atem18** [comment]
Hi @p0nt,

I am glad you like it.

If you speak about Websockets, yes it does reconnect if you don't have internet, you can test it by running the cli.py program.
It's not yet a proper CLI for kraken but it implements a dump Websockets connection.
Switch off your internet connection, you will see it pause and when you resume your internet connection, it will reconnect.

If you speak about the API, there is not (yet?) the ability to retry because for one hand there is no proper support (yet?) in HTTPX and on a second hand, I am not sure you would want to retry all the API requests like creating an order for example.

If you have more questions, please ask.

**Comment by p0nt** [comment]
Hi Atem18,

Thank you for the awesome quick response, sorry that I've not stated this in my question... I was indeed talking about websocket.

This means the question is answered, thank you very much!
